//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geta.Optimizely.ContentTypeIcons
{
    /// <summary>
    /// Font Awesome. Version 7.2.0.
    /// </summary>
    public enum FontAwesome7Regular
    {
        /// <summary>
        /// Address Book (address-book)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: address, address book, contact, contact list, contacts, directory, employee, little black book, people, personal organizer, phone book, profile, rolodex, user, username</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.0.3, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        AddressBook = 0xf2b9,

        /// <summary>
        /// Address Card (address-card)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: address, badge, business card, card, contact, contact card, credentials, employee, id, id card, identification, name card, personal info, profile, profile card, registration, user</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.0.3, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        AddressCard = 0xf2bb,

        /// <summary>
        /// Alarm Clock (alarm-clock)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: alarm, alarm clock, alert, bedtime, clock, deadline, morning, reminder, ringing, schedule, snooze, stopwatch, time, timer, wake up, watch</para>
        /// <para>Added in 5.0.0, updated in 5.9.0, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        AlarmClock = 0xf34e,

        /// <summary>
        /// Bell (bell)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: alarm, alert, bell, buzzer, call, chime, ding, notification, prompt, reminder, request, ring, signal, tone</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.11.0, 5.2.0, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Bell = 0xf0f3,

        /// <summary>
        /// Bell Slash (bell-slash)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: alert, bell, block, cancel, disable notifications, disabled, do not disturb, mute, no sound, notification, off, quiet, reminder, silent, sound off</para>
        /// <para>Added in 4.2.0, updated in 5.0.0, 5.2.0, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        BellSlash = 0xf1f6,

        /// <summary>
        /// Bookmark (bookmark)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bookmark, clip, favorite, flag, hold, keep, mark, marker, page, read, remember, research, ribbon, save, tag</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.1.2, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Bookmark = 0xf02e,

        /// <summary>
        /// Building (building)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: apartment, architecture, building, business, city, company, corporate, headquarters, office, office building, real estate, skyscraper, tower, urban, workplace</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Building = 0xf1ad,

        /// <summary>
        /// Calendar (calendar)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: agenda, appointment, calendar, date, day, deadline, event, month, planner, reminder, schedule, time, year</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Calendar = 0xf133,

        /// <summary>
        /// Calendar Check (calendar-check)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: accept, agree, appointment, approved, booked, calendar, check, completed, confirm, confirmed, date, day, deadline, done, event, mark, meeting, month, planned, reminder, schedule, select, success, tick, time, todo, validate</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0, 7.0.1 and 7.1.0.</para>
        /// </summary>
        CalendarCheck = 0xf274,

        /// <summary>
        /// Calendar Days (calendar-days)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: agenda, appointment, calendar, date, day, deadline, event, month, planner, reminder, schedule, time, timeline, year</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.10.2, 5.6.0, 5.7.0, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CalendarDays = 0xf073,

        /// <summary>
        /// Calendar Minus (calendar-minus)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: calendar, cancel, clear, date, day, delete, event, minus, month, reduce, remove, schedule, subtract, time, year</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CalendarMinus = 0xf272,

        /// <summary>
        /// Calendar Plus (calendar-plus)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: add, appointment, calendar, create, date, day, event, month, new, plan, plus, reminder, schedule, time, year</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        CalendarPlus = 0xf271,

        /// <summary>
        /// Calendar Xmark (calendar-xmark)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: appointment, calendar, cancel, cancelation, close, date, day, delete, event, month, remove, schedule, time, x, year</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CalendarXmark = 0xf273,

        /// <summary>
        /// Camera (camera)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: camera, camera icon, capture, film, image, lens, photo, photograph, photography, picture, recording, shutter, snapshot, video</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta2, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Camera = 0xf030,

        /// <summary>
        /// Chart Bar (chart-bar)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: analytics, bar, chart, comparison, dashboard, data, graph, metrics, performance, progress, report, statistics, trends, visualization</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.3.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChartBar = 0xf080,

        /// <summary>
        /// Chess Bishop (chess-bishop)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bishop, black bishop, board game, checkmate, chess, chess piece, chessboard, game piece, strategy</para>
        /// <para>Added in 5.0.5, updated in 5.9.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChessBishop = 0xf43a,

        /// <summary>
        /// Chess King (chess-king)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: board game, checkmate, chess, chess king, chess piece, chess strategy, chessboard, game, king, king piece, strategy</para>
        /// <para>Added in 5.0.5, updated in 5.9.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChessKing = 0xf43f,

        /// <summary>
        /// Chess Knight (chess-knight)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: board game, checkmate, chess, chess match, chess piece, chessboard, game piece, horse, knight, strategy</para>
        /// <para>Added in 5.0.5, updated in 5.9.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChessKnight = 0xf441,

        /// <summary>
        /// Chess Pawn (chess-pawn)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: board game, checkmate, chess, chess pawn, expendable, game piece, pawn, piece, sacrifice, strategy</para>
        /// <para>Added in 5.0.5, updated in 5.9.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChessPawn = 0xf443,

        /// <summary>
        /// Chess Queen (chess-queen)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: board game, checkmate, chess, chess piece, chess queen, chess set, chessboard, game, queen, queen piece, strategy</para>
        /// <para>Added in 5.0.5, updated in 5.9.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChessQueen = 0xf445,

        /// <summary>
        /// Chess Rook (chess-rook)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: board game, castle, checkmate, chess piece, chess strategy, chessboard, defense, game piece, rook, strategy, tower</para>
        /// <para>Added in 5.0.5, updated in 5.9.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ChessRook = 0xf447,

        /// <summary>
        /// Circle (circle)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: black circle, blue circle, brown circle, circle, diameter, dot, ellipse, fill, geometric, green circle, indicator, notification, orange circle, progress, purple circle, red circle, round, shape, status, white circle, yellow circle</para>
        /// <para>Added in 3.0.0, updated in 5.0.0, 5.10.1, 5.10.2, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Circle = 0xf111,

        /// <summary>
        /// Circle Check (circle-check)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: accept, agree, approve, check, confirm, correct, done, enable, ok, select, success, tick, validate, yes</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0, 7.0.1 and 7.1.0.</para>
        /// </summary>
        CircleCheck = 0xf058,

        /// <summary>
        /// Circle Dot (circle-dot)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bullseye, button, circle, dot, focus, indicator, marker, notification, point, radio, radio button, target</para>
        /// <para>Added in 4.0.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.0.1.</para>
        /// </summary>
        CircleDot = 0xf192,

        /// <summary>
        /// Circle Down (circle-down)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow-circle-down, arrow-down, circle-arrow-down, circle-download, download, download-button, download-circle, downward-arrow, save, save-file</para>
        /// <para>Added in 5.0.0, updated in 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CircleDown = 0xf358,

        /// <summary>
        /// Circle Left (circle-left)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, arrow-circle-left, back, circle, go back, left, navigation, previous, return, undo</para>
        /// <para>Added in 5.0.0, updated in 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CircleLeft = 0xf359,

        /// <summary>
        /// Circle Pause (circle-pause)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: break, halt, hold, media control, pause, pause button, stop, temporary stop, wait, waiting</para>
        /// <para>Added in 4.5.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CirclePause = 0xf28b,

        /// <summary>
        /// Circle Play (circle-play)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: audio, clip, media, movie, music, play, sound, start, streaming, video, watch</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 5.10.2, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CirclePlay = 0xf144,

        /// <summary>
        /// Circle Question (circle-question)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: ask, assist, confusion, doubt, faq, help, info, information, inquiry, query, question, question-mark, support, unknown</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        CircleQuestion = 0xf059,

        /// <summary>
        /// Circle Right (circle-right)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, arrow-circle-o-right, circle, continue, direction, forward, move, navigation, next, proceed, right</para>
        /// <para>Added in 5.0.0, updated in 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CircleRight = 0xf35a,

        /// <summary>
        /// Circle Stop (circle-stop)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: block, cancel, circle, deny, disallow, forbidden, halt, no, pause, prevent, prohibit, stop</para>
        /// <para>Added in 4.5.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CircleStop = 0xf28d,

        /// <summary>
        /// Circle Up (circle-up)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, arrow-circle-up, circle, direction up, increase, move up, up, upgrade, upload, upload arrow</para>
        /// <para>Added in 5.0.0, updated in 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CircleUp = 0xf35b,

        /// <summary>
        /// Circle User (circle-user)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: account, avatar, contact, employee, individual, member, people, person, profile, user, username</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.0.11, 5.0.3, 5.11.0, 5.11.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        CircleUser = 0xf2bd,

        /// <summary>
        /// Circle Xmark (circle-xmark)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cancel, close, cross, dismiss, error, exit, fail, incorrect, no, reject, remove, stop, wrong, xmark</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CircleXmark = 0xf057,

        /// <summary>
        /// Clipboard (clipboard)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: board, checklist, clipboard, copy, document, file, memo, notepad, notes, paper, paste, record, task, writing</para>
        /// <para>Added in 5.0.0, updated in 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Clipboard = 0xf328,

        /// <summary>
        /// Clock (clock)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: 4, 4:00, alarm, clock, four, four o’clock, hour, late, minute, o&apos;clock, pending, schedule, ticking, time, timer, timestamp, watch</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.12.1, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Clock = 0xf017,

        /// <summary>
        /// Clone (clone)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: add, backup, clone, copy, copy-paste, duplicate, mirror, new, repeat, replicate, replicate</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.11.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Clone = 0xf24d,

        /// <summary>
        /// Closed Captioning (closed-captioning)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: accessibility, captions, cc, closed caption, closed captions, deaf, hearing impaired, subtitle, subtitles, text, transcript, video</para>
        /// <para>Added in 4.2.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        ClosedCaptioning = 0xf20a,

        /// <summary>
        /// Cloud (cloud)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: atmosphere, backup, cloud, data, fog, internet, network, online, overcast, save, sky, storage, upload, weather</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.0.11, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Cloud = 0xf0c2,

        /// <summary>
        /// Comment (comment)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: chat, comment, conversation, discussion, feedback, message, note, notification, reply, response, sms, speech bubble, talk, texting</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.0.9, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Comment = 0xf075,

        /// <summary>
        /// Comment Dots (comment-dots)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bubble, chat, comment, conversation, dialog, discussion, feedback, input, message, note, reply, sms, speech balloon, texting, typing</para>
        /// <para>Added in 5.0.9, updated in 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        CommentDots = 0xf4ad,

        /// <summary>
        /// Comments (comments)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: chat, comment, communication, conversation, dialogue, discussion, feedback, message, notification, reply, sms, speech bubbles, talk, texting</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.0.9, 6.0.0-beta1, 6.0.0-beta2, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Comments = 0xf086,

        /// <summary>
        /// Compass (compass)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: adventure, compass, directions, explore, guide, location, magnetic, map, navigation, north, orienteering, path, route, travel, wayfinding</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.11.0, 5.11.1, 5.2.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Compass = 0xf14e,

        /// <summary>
        /// Copy (copy)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: clipboard, clone, copy, document, duplicate, file, paper, paste, replicate, replicate, replicate</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Copy = 0xf0c5,

        /// <summary>
        /// Copyright (copyright)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: c, copyright, copyright symbol, intellectual property, legal, license, mark, protection, registered, rights, trademark</para>
        /// <para>Added in 4.2.0, updated in 5.0.0, 5.10.1, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Copyright = 0xf1f9,

        /// <summary>
        /// Credit Card (credit-card)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: billing, buy, card, charge, checkout, credit card, debit card, finance, money, pay, payment, plastic card, purchase, transaction, wallet</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        CreditCard = 0xf09d,

        /// <summary>
        /// Envelope (envelope)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: contact, correspondence, e-mail, email, envelope, inbox, letter, mail, message, newsletter, notification, postal, receive, send, support</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.10.1, 5.10.2, 6.0.0-beta1, 6.1.0, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Envelope = 0xf0e0,

        /// <summary>
        /// Envelope Open (envelope-open)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: communication, correspondence, e-mail, email, inbox, letter, mail, message, newsletter, notification, offer, open mail, support</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.10.1, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        EnvelopeOpen = 0xf2b6,

        /// <summary>
        /// Eye (eye)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: eye, focus, glimpse, look, observe, peek, see, sight, stare, view, visible, vision, watch</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.7.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Eye = 0xf06e,

        /// <summary>
        /// Eye Slash (eye-slash)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: blocked, conceal, disable, eye, hidden, hide, invisible, no-view, obscured, privacy, privacy-mode, security, toggle, unseen</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.7.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        EyeSlash = 0xf070,

        /// <summary>
        /// Face Angry (face-angry)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: angry, annoyed, disapprove, displeased, emoticon, emotion, face, frowning, frustrated, glare, mad, rage, upset</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceAngry = 0xf556,

        /// <summary>
        /// Face Dizzy (face-dizzy)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: confused, dazed, dizzy, dizzy face, emoticon, face, faint, sick, unwell, woozy, woozy face</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceDizzy = 0xf567,

        /// <summary>
        /// Face Flushed (face-flushed)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bashful, blushing, embarrassed, emoticon, face, flushed, overwhelmed, red-faced, shy, surprised</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceFlushed = 0xf579,

        /// <summary>
        /// Face Frown (face-frown)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: disappointed, disapprove, displeased, emoticon, face, frown, frowning face, negative, sad, unhappy, unhappy emoji, unhappy face</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 5.0.9, 5.1.0, 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        FaceFrown = 0xf119,

        /// <summary>
        /// Face Frown Open (face-frown-open)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: disappointed, disapprove, displeased, emoticon, expression, face, frown, negative, open mouth, sad, unhappy, upset</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceFrownOpen = 0xf57a,

        /// <summary>
        /// Face Grimace (face-grimace)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: anxious, awkward, cringe, emoticon, expression, face, grimace, grimacing face, nervous, teeth, uncomfortable, uneasy, worried</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrimace = 0xf57f,

        /// <summary>
        /// Face Grin (face-grin)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: amusement, cheerful, emoji, expression, face, grin, grinning, happy, joy, laugh, pleased, smile</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrin = 0xf580,

        /// <summary>
        /// Face Grin Beam (face-grin-beam)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: beam, cheerful, delighted, emoticon, eyes closed, face, grin, happy, joy, laugh, open mouth, smile, smiling face</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinBeam = 0xf582,

        /// <summary>
        /// Face Grin Beam Sweat (face-grin-beam-sweat)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: anxious, awkward, beam, embarrassed, emoticon, face, grin, nervous, relief, smile, sweat, uncomfortable</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinBeamSweat = 0xf583,

        /// <summary>
        /// Face Grin Hearts (face-grin-hearts)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: admiration, adoration, affection, crush, emoji, emoticon, face, heart-eyes, infatuation, love, smile, smiling</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinHearts = 0xf584,

        /// <summary>
        /// Face Grin Squint (face-grin-squint)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: amusement, emoticon, face, grin, happy, joy, laugh, laughing, playful, satisfied, smile, squint</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinSquint = 0xf585,

        /// <summary>
        /// Face Grin Squint Tears (face-grin-squint-tears)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: emoji, face, funny, grin, happy, humor, joy, laugh, laughing, rofl, rolling on the floor laughing, smile, squint, tears</para>
        /// <para>Added in 5.1.0, updated in 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinSquintTears = 0xf586,

        /// <summary>
        /// Face Grin Stars (face-grin-stars)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: amazed, celebrity, emoticon, excited, face, grin, happy, impressed, joyful, smiling, star, star-struck, starry-eyed, vip</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinStars = 0xf587,

        /// <summary>
        /// Face Grin Tears (face-grin-tears)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: LOL, crying with laughter, emoji, face, funny, grin, happy, joy, laugh, laughing, smile, tear, tears of joy</para>
        /// <para>Added in 5.1.0, updated in 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinTears = 0xf588,

        /// <summary>
        /// Face Grin Tongue (face-grin-tongue)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cheeky, emoji, face, funny, goofy, grin, joking, laugh, lighthearted, playful, silly, teasing, tongue</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinTongue = 0xf589,

        /// <summary>
        /// Face Grin Tongue Squint (face-grin-tongue-squint)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: emoji, face, funny, goofy, grin, joking, laugh, playful, silly, silly face, squint, teasing, tongue</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinTongueSquint = 0xf58a,

        /// <summary>
        /// Face Grin Tongue Wink (face-grin-tongue-wink)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: LOL, cheeky, emoji, emoticon, face, funny, grin, joke, laugh, playful, silly, teasing, tongue, wink, winking face</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 5.12.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinTongueWink = 0xf58b,

        /// <summary>
        /// Face Grin Wide (face-grin-wide)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: big eyes, cheerful, emoticon, excited, face, grin, happy, joyful, laugh, open mouth, smile, wide grin</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinWide = 0xf581,

        /// <summary>
        /// Face Grin Wink (face-grin-wink)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cheeky, emoticon, face, flirt, grin, happy, mischievous, playful, smile, wink</para>
        /// <para>Added in 5.1.0, updated in 5.1.1, 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceGrinWink = 0xf58c,

        /// <summary>
        /// Face Kiss (face-kiss)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: affection, beso, blowing a kiss, emoji, face, flirt, hug and kiss, kiss, kissing face, love, romantic, smooch</para>
        /// <para>Added in 5.1.0, updated in 5.1.1, 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.5.2, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceKiss = 0xf596,

        /// <summary>
        /// Face Kiss Beam (face-kiss-beam)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: affection, blowing kiss, emoji, emoticon, eyes closed, face, happy, kiss, kissing face, love, smile, smooch</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.5.2, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceKissBeam = 0xf597,

        /// <summary>
        /// Face Kiss Wink Heart (face-kiss-wink-heart)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: affection, blowing a kiss, emoji, emoticon, face, flirt, heart, kiss, love, smooch, wink</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.5.2, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceKissWinkHeart = 0xf598,

        /// <summary>
        /// Face Laugh (face-laugh)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: amusement, chuckle, emoji, face, funny, grin, happy, humor, joy, laugh, laughter, smile</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        FaceLaugh = 0xf599,

        /// <summary>
        /// Face Laugh Beam (face-laugh-beam)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: amusement, beaming face, cheerful, emoji, fun, grin, happy, humor, joy, laugh, laughing face, laughter, smile, smiling eyes</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceLaughBeam = 0xf59a,

        /// <summary>
        /// Face Laugh Squint (face-laugh-squint)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: LOL, amused, emoticon, face, funny, grin, happy, joy, laugh, laughing, smile, squint</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceLaughSquint = 0xf59b,

        /// <summary>
        /// Face Laugh Wink (face-laugh-wink)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: LOL, emoticon, face, funny, happy, humor, joking, laugh, playful, smile, wink</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceLaughWink = 0xf59c,

        /// <summary>
        /// Face Meh (face-meh)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: apathetic, bland, deadpan, default, emoticon, emotion, expression, face, indifferent, meh, neutral, neutral face, rating, unamused, unimpressed</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 5.0.9, 5.1.0, 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        FaceMeh = 0xf11a,

        /// <summary>
        /// Face Meh Blank (face-meh-blank)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: blank, deadpan, emotionless, expressionless, face, indifferent, meh, neutral, no mouth, quiet, silent, stoic, unimpressed</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceMehBlank = 0xf5a4,

        /// <summary>
        /// Face Rolling Eyes (face-rolling-eyes)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: annoyed, dismissive, emoji, exasperated, expression, eye roll, eyeroll, face, reaction, rolling eyes, sarcastic, unimpressed</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceRollingEyes = 0xf5a5,

        /// <summary>
        /// Face Sad Cry (face-sad-cry)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: crying, emoticon, emotional, face, sad face, sobbing, tearful, tears, unhappy, upset</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceSadCry = 0xf5b3,

        /// <summary>
        /// Face Sad Tear (face-sad-tear)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: crying, distress, emoticon, emotional, face, grief, sad, sorrow, tear, tears, unhappy, upset</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceSadTear = 0xf5b4,

        /// <summary>
        /// Face Smile (face-smile)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: approve, cheerful, content, emoticon, face, friendly, happy, joy, pleased, positive, satisfied, slightly smiling face, smile</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 5.0.9, 5.1.0, 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        FaceSmile = 0xf118,

        /// <summary>
        /// Face Smile Beam (face-smile-beam)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: beaming, blush, cheerful, delighted, emoticon, face, grin, happiness, happy, joyful, pleased, positive, smile, smiling</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceSmileBeam = 0xf5b8,

        /// <summary>
        /// Face Smile Wink (face-smile-wink)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cheeky, emoticon, face, flirt, fun, happy, mischievous, playful, smile, teasing, wink, winking face</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceSmileWink = 0xf4da,

        /// <summary>
        /// Face Surprise (face-surprise)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: astonished, emoji, expression, face, open mouth, reaction, shocked, startled, surprised, wow</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceSurprise = 0xf5c2,

        /// <summary>
        /// Face Tired (face-tired)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: drained, emoticon, exhausted, face, fatigued, frustrated, grumpy, sleepy, tired, upset, weary, worn out</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FaceTired = 0xf5c8,

        /// <summary>
        /// File (file)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: blank, cv, document, file, form, new, page, page facing up, paper, pdf, report, resume, sheet, text</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.10.1, 5.10.2, 6.0.0-beta1, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        File = 0xf15b,

        /// <summary>
        /// File Audio (file-audio)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: audio, document, file, mp3, music, play, recording, sound, track, waveform</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileAudio = 0xf1c7,

        /// <summary>
        /// File Code (file-code)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: code, css, development, document, file, html, markup, mysql, programming, script, sql</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileCode = 0xf1c9,

        /// <summary>
        /// File Excel (file-excel)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: csv, data, document, excel, microsoft excel, numbers, sheet, spreadsheet, table, workbook, xls, xlsx</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileExcel = 0xf1c3,

        /// <summary>
        /// File Image (file-image)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: document, document with image, file, graphic, image, image file, img, jpg, photo, photo file, picture, picture file, png</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileImage = 0xf1c5,

        /// <summary>
        /// File Lines (file-lines)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: document, file, file-text, form, invoice, new document, page, paper, pdf, report, sheet, text</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileLines = 0xf15c,

        /// <summary>
        /// File Pdf (file-pdf)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: acrobat, attachment, document, ebook, file, pdf, portable document format, preview, report, save</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.5.1, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FilePdf = 0xf1c1,

        /// <summary>
        /// File Powerpoint (file-powerpoint)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: deck, document, file, keynote, microsoft, office, powerpoint, ppt, presentation, slide, slideshow</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FilePowerpoint = 0xf1c4,

        /// <summary>
        /// File Video (file-video)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: clip, file, film, footage, m4v, media, movie, mp4, play, playback, recording, video</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileVideo = 0xf1c8,

        /// <summary>
        /// File Word (file-word)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: doc, document, editable, file, letter, office, page, paper, report, text, word, word processing, writing</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileWord = 0xf1c2,

        /// <summary>
        /// File Zipper (file-zipper)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: .zip, archive, archive file, bundle, compress, compressed, compression, download, extractor, file, folder, packed, packing, zip, zipped file</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 5.10.2, 5.7.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FileZipper = 0xf1c6,

        /// <summary>
        /// Flag (flag)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: alert, banner, country, flag, marker, nation, notification, notify, pennant, pole, report, signal, symbol, waving</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Flag = 0xf024,

        /// <summary>
        /// Floppy Disk (floppy-disk)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: archive, backup, computer, data, disk, floppy, floppy disk, legacy, memory, old school, retro, save, save icon, storage</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        FloppyDisk = 0xf0c7,

        /// <summary>
        /// Folder (folder)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: archive, directory, document, documents, file, file folder, file organizer, files, filing, folder, folder icon, folder symbol, storage</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.10.1, 5.3.0, 6.0.0-beta1, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Folder = 0xf07b,

        /// <summary>
        /// Folder Closed (folder-closed)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: archive, closed folder, directory, documents, file cabinet, file folder, filing, folder, organize, storage</para>
        /// <para>Added in 6.0.0-beta1, updated in 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FolderClosed = 0xe185,

        /// <summary>
        /// Folder Open (folder-open)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: archive, directory, document, file, file folder, folder, folder icon, folder open, folder view, open, open file folder, open folder</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        FolderOpen = 0xf07c,

        /// <summary>
        /// Font Awesome (font-awesome)
        /// <para>Styles: solid, regular, brands</para>
        /// <para>Terms: branding, fa, font-awesome, icon set, logo, typeface</para>
        /// <para>Added in 4.6.0, updated in 5.0.0, 5.15.4, 6.0.0-beta1, 6.1.2, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.5.2, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        FontAwesome = 0xf2b4,

        /// <summary>
        /// Futbol (futbol)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: ball, football, football game, football sport, soccer, soccer ball, soccer ball graphic, soccer ball icon, soccer ball symbol, soccer game, soccer sport, sports</para>
        /// <para>Added in 4.2.0, updated in 5.0.0, 5.0.5, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Futbol = 0xf1e3,

        /// <summary>
        /// Gem (gem)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: crystal, diamond, emerald, gem, gem stone, gemstone, jewel, jewelry, luxury, precious, ruby, sapphire, treasure, valuable</para>
        /// <para>Added in 5.0.0, updated in 5.10.1, 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Gem = 0xf3a5,

        /// <summary>
        /// Hand (hand)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: backhand, gesture, halt, hand, high five, palm, raised hand, request, roshambo, signal, stop, wave</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Hand = 0xf256,

        /// <summary>
        /// Hand Back Fist (hand-back-fist)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: closed hand, fist, game, gesture, hand, punch, rock, roshambo, strike</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandBackFist = 0xf255,

        /// <summary>
        /// Hand Lizard (hand-lizard)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: claw, game, hand gesture, lizard, reptile, rock paper scissors, roshambo, sign</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandLizard = 0xf258,

        /// <summary>
        /// Hand Peace (hand-peace)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: gesture, hand, peace, peace sign, sign, symbol, truce, two fingers, v, victory, victory hand</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandPeace = 0xf25b,

        /// <summary>
        /// Hand Point Down (hand-point-down)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, click, cursor, direction, down, finger, gesture, hand, indicator, point, pointing, select, tap</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandPointDown = 0xf0a7,

        /// <summary>
        /// Hand Point Left (hand-point-left)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, back, direction, finger, gesture, hand, indicate, left, point, pointer, previous, select</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandPointLeft = 0xf0a5,

        /// <summary>
        /// Hand Point Right (hand-point-right)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, direction, finger, forward, gesture, hand, next, point, pointer, right</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandPointRight = 0xf0a4,

        /// <summary>
        /// Hand Point Up (hand-point-up)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: click, direction, finger, gesture, hand, index, indicate, point up, pointing up, request, select, up, upgrade</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandPointUp = 0xf0a6,

        /// <summary>
        /// Hand Pointer (hand-pointer)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: click, cursor, gesture, hand, hand-cursor, interact, pointer, select, tap, touch</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandPointer = 0xf25a,

        /// <summary>
        /// Hand Scissors (hand-scissors)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cut, fingers, game, hand gesture, peace sign, rock paper scissors, roshambo, scissors, victory</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandScissors = 0xf257,

        /// <summary>
        /// Hand Spock (hand-spock)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: finger, gesture, greeting, hand, hello, live long, peace, prosper, salute, sci-fi, sign, spock, star trek, vulcan, vulcan salute</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.12.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HandSpock = 0xf259,

        /// <summary>
        /// Handshake (handshake)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: agreement, alliance, collaboration, contract, cooperation, deal, greeting, handshake, meeting, negotiation, partnership, trust, welcome</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.0.9, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Handshake = 0xf2b5,

        /// <summary>
        /// Hard Drive (hard-drive)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: backup, computer, data, device, disk, drive, hard disk, hard drive, hardware, hdd, save, storage, storage device</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        HardDrive = 0xf0a0,

        /// <summary>
        /// Headphones (headphones)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: audio, audio device, earbuds, earphones, headphones, headset, listen, music, music player, sound, stereo</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Headphones = 0xf025,

        /// <summary>
        /// Heart (heart)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: affection, card, emotion, favorite, heart, heart suit, like, love, passion, playing card, relationship, romance, symbol, valentine, wishlist</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.0.9, 5.10.1, 5.10.2, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Heart = 0xf004,

        /// <summary>
        /// Hospital (hospital)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: ER, ambulance, building, clinic, covid-19, doctor, emergency, health, healthcare, hospital, medical center, medicine, nurse, treatment</para>
        /// <para>Added in 3.0.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Hospital = 0xf0f8,

        /// <summary>
        /// Hourglass (hourglass)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: countdown, hourglass, hourglass not done, loading, minute, sand, stopwatch, time, timer, waiting</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.1.2, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Hourglass = 0xf254,

        /// <summary>
        /// Hourglass Half (hourglass-half)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: clock, countdown, delay, hourglass, hourglass-half, pending, sand, stopwatch, time, timer, waiting</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.1.2, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        HourglassHalf = 0xf252,

        /// <summary>
        /// House (house)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: abode, building, domicile, dwelling, home, house, living place, main, property, real estate, residence, shelter</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.7.0, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        House = 0xf015,

        /// <summary>
        /// Id Badge (id-badge)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: badge, card, contact, credential, id, identification, identity, license, name tag, profile, user, username</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.0.3, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        IdBadge = 0xf2c1,

        /// <summary>
        /// Id Card (id-card)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: badge, card, contact, credentials, demographics, document, id, identification, identity, license, personal, profile, registration, user, username</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.0.3, 5.10.1, 5.8.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        IdCard = 0xf2c2,

        /// <summary>
        /// Image (image)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: gallery, image, image file, landscape, photo, photo album, photograph, picture, picture frame, snapshot</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Image = 0xf03e,

        /// <summary>
        /// Images (images)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: album, gallery, image, landscape, media, photo, photo album, photo gallery, photograph, picture, picture frame, snapshot</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Images = 0xf302,

        /// <summary>
        /// Keyboard (keyboard)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: accessory, computer, data entry, device, hardware, input, keyboard, keypad, keys, text, type, typing, write</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Keyboard = 0xf11c,

        /// <summary>
        /// Lemon (lemon)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: citrus, citrus fruit, fruit, lemon, lemonade, refreshing, sour, summer, tart, vitamin C, yellow</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Lemon = 0xf094,

        /// <summary>
        /// Life Ring (life-ring)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: coast guard, emergency, flotation, help, life preserver, lifebuoy, lifesaver, overboard, rescue, safety, save, support</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        LifeRing = 0xf1cd,

        /// <summary>
        /// Lightbulb (lightbulb)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bright, bulb, concept, creativity, electric, electricity, energy, idea, innovation, inspiration, invention, lamp, light, light bulb, thinking</para>
        /// <para>Added in 3.0.0, updated in 5.0.0, 5.3.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Lightbulb = 0xf0eb,

        /// <summary>
        /// Map (map)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: address, atlas, chart, coordinates, destination, directions, gps, guide, location, map, navigation, pin, place, point of interest, position, route, travel, world, world map</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.1.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Map = 0xf279,

        /// <summary>
        /// Message (message)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bubble, chat, comment, conversation, discussion, feedback, message, note, notification, reply, sms, speech, talk, text, texting</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Message = 0xf27a,

        /// <summary>
        /// Money Bill 1 (money-bill-1)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bill, buy, cash, checkout, currency, dollar, finance, money, paycheck, payment, premium, price, purchase, salary</para>
        /// <para>Added in 5.0.0, updated in 5.0.13, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        MoneyBill1 = 0xf3d1,

        /// <summary>
        /// Moon (moon)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: crescent, crescent moon, dark, dark mode, evening, lunar, moon, moonlight, night, night mode, nighttime, nighttime symbol, sleep</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.11.0, 5.11.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Moon = 0xf186,

        /// <summary>
        /// Newspaper (newspaper)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: article, bulletin, editorial, gazette, headline, journalism, media, news, newsletter, newspaper, paper, periodical, press, publication, report</para>
        /// <para>Added in 4.2.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Newspaper = 0xf1ea,

        /// <summary>
        /// Note Sticky (note-sticky)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: annotation, label, memo, message, note, paper, post-it, reminder, sticker, sticky note</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        NoteSticky = 0xf249,

        /// <summary>
        /// Object Group (object-group)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cluster, collection, combine, copy, design, group, layers, merge, objects, select</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.1, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ObjectGroup = 0xf247,

        /// <summary>
        /// Object Ungroup (object-ungroup)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: break apart, design, divide, layers, objects, select, separate, split, ungroup</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.1, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ObjectUngroup = 0xf248,

        /// <summary>
        /// Paper Plane (paper-plane)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: air, communication, delivery, flight, float, folded paper, mail, message, paper, paper aeroplane, paper airplane, plane, send, send message</para>
        /// <para>Added in 4.1.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        PaperPlane = 0xf1d8,

        /// <summary>
        /// Paste (paste)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: clipboard, clipboard-insert, clipboard-paste, content, document, input, insert, paper, paste, text</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Paste = 0xf0ea,

        /// <summary>
        /// Pen To Square (pen-to-square)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: annotate, change, compose, document, draft, edit, form, input, modify, note, pen, pencil, signature, update, write</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        PenToSquare = 0xf044,

        /// <summary>
        /// Rectangle List (rectangle-list)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: checklist, completed, done, finished, items, list, notes, outline, summary, tasks, todo</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        RectangleList = 0xf022,

        /// <summary>
        /// Rectangle Xmark (rectangle-xmark)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cancel, clear, close, delete, dismiss, exit, rectangle, reject, remove, stop, window, xmark</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        RectangleXmark = 0xf410,

        /// <summary>
        /// Registered (registered)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: copyright-related, intellectual property, legal, mark, r, registered, symbol, trademark</para>
        /// <para>Added in 4.4.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        Registered = 0xf25d,

        /// <summary>
        /// Share From Square (share-from-square)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, distribute, export, forward, link, send, send-to, share, social, upload</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.2.1, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        ShareFromSquare = 0xf14d,

        /// <summary>
        /// Snowflake (snowflake)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: blizzard, cold, freeze, frost, ice, precipitation, snow, snowfall, snowflake, winter</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.5.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Snowflake = 0xf2dc,

        /// <summary>
        /// Square (square)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: black square, block, box, geometric, quadrilateral, rectangle, shape, solid square, square, square shape, white square</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.10.1, 5.10.2, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Square = 0xf0c8,

        /// <summary>
        /// Square Caret Down (square-caret-down)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, caret, down, dropdown, expand, indicator, menu, more, navigation, pointer, square, toggle, triangle</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquareCaretDown = 0xf150,

        /// <summary>
        /// Square Caret Left (square-caret-left)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, back, caret, direction, left, navigation, pointer, previous, square, triangle</para>
        /// <para>Added in 4.0.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquareCaretLeft = 0xf191,

        /// <summary>
        /// Square Caret Right (square-caret-right)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, arrowhead, caret, forward, navigation, next, play, pointer, right, skip, square, triangle</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquareCaretRight = 0xf152,

        /// <summary>
        /// Square Caret Up (square-caret-up)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: arrow, arrow-up, arrowhead, caret, caret-square-o-up, collapse, expand, increase, pointer, square, triangle, up, up arrow, up caret, upload</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquareCaretUp = 0xf151,

        /// <summary>
        /// Square Check (square-check)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: accept, agree, box, button, check, check mark, checkbox, checkmark, confirm, correct, done, enable, mark, ok, select, success, tick, validate, yes</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.0.1.</para>
        /// </summary>
        SquareCheck = 0xf14a,

        /// <summary>
        /// Square Full (square-full)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: block, color block, colored square, filled square, geometric shape, shape, solid square, square</para>
        /// <para>Added in 5.0.5, updated in 5.10.2, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquareFull = 0xf45c,

        /// <summary>
        /// Square Minus (square-minus)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: close, collapse, hide, hide-content, minimize, minus, negative, reduce, remove, shrink, square, subtract</para>
        /// <para>Added in 3.1.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquareMinus = 0xf146,

        /// <summary>
        /// Square Plus (square-plus)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: add, box, create, expand, increase, more, new, plus, positive, shape, square</para>
        /// <para>Added in 3.0.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        SquarePlus = 0xf0fe,

        /// <summary>
        /// Star (star)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: achievement, award, bookmark, favorite, favorite item, highlight, important, night, premium, quality, rating, score, star, top, vip</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.10.2, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Star = 0xf005,

        /// <summary>
        /// Star Half (star-half)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: achievement, award, feedback, half star, half-filled star, partial rating, rating, review, score, star half, star outline</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        StarHalf = 0xf089,

        /// <summary>
        /// Star Half Stroke (star-half-stroke)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: achievement, award, favorite, feedback, half star, partial rating, rating, review, score, star half, star half empty, star half full</para>
        /// <para>Added in 5.1.0, updated in 5.11.0, 5.11.1, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        StarHalfStroke = 0xf5c0,

        /// <summary>
        /// Sun (sun)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bright, daylight, daytime, rays, sol, solar, star, sun, sunlight, sunny, sunshine, warmth, weather</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.5.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Sun = 0xf185,

        /// <summary>
        /// Thumbs Down (thumbs-down)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: disagree, disapprove, dislike, dislike button, downvote, hand gesture, negative, no, thumb down, thumbs down, thumbs-o-down</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        ThumbsDown = 0xf165,

        /// <summary>
        /// Thumbs Up (thumbs-up)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: +1, agree, approve, endorsement, good, hand, like, ok, okay, positive, recommend, social, success, support, thumb, thumbs up, vote, yes</para>
        /// <para>Added in 3.2.0, updated in 5.0.0, 5.10.2, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        ThumbsUp = 0xf164,

        /// <summary>
        /// Trash Can (trash-can)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: bin, delete, discard, dumpster, garbage, recycle, remove, rubbish, trash, trashcan, waste</para>
        /// <para>Added in 5.0.0, updated in 5.10.2, 5.7.0, 6.0.0, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        TrashCan = 0xf2ed,

        /// <summary>
        /// Truck (truck)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: cargo, delivery, delivery truck, freight, hauler, lorry, pickup, shipping, transport, truck, truck icon, vehicle</para>
        /// <para>Added in 2.0.0, updated in 5.0.0, 5.0.7, 6.0.0-beta1, 6.0.0-beta2, 6.0.0-beta3, 6.1.0, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        Truck = 0xf0d1,

        /// <summary>
        /// User (user)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: account, avatar, default, employee, gender-neutral, identity, individual, member, person, profile, silhouette, user, username</para>
        /// <para>Added in 1.0.0, updated in 5.0.0, 5.0.11, 5.0.3, 6.0.0-beta1, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0, 7.0.0 and 7.1.0.</para>
        /// </summary>
        User = 0xf007,

        /// <summary>
        /// Window Maximize (window-maximize)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: UI, browser, computer, enlarge, expand, fullscreen, interface, maximize, screen, window</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        WindowMaximize = 0xf2d0,

        /// <summary>
        /// Window Minimize (window-minimize)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: UI, collapse, desktop, hide, interface, minimize, reduce, screen, shrink, window</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 5.10.1, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        WindowMinimize = 0xf2d1,

        /// <summary>
        /// Window Restore (window-restore)
        /// <para>Styles: solid, regular</para>
        /// <para>Terms: application, browser, computer, desktop, interface, maximize, resize, restore, screen, window</para>
        /// <para>Added in 4.7.0, updated in 5.0.0, 6.0.0-beta1, 6.0.0-beta3, 6.2.0, 6.3.0, 6.4.0, 6.5.0, 6.6.0, 6.7.0 and 7.0.0.</para>
        /// </summary>
        WindowRestore = 0xf2d2,

    }
}
